name: mirroracle
description: "Mirroracle Flutter starter with Supabase auth + sessions insert."
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.6.0
  camera: ^0.11.3
  wakelock_plus: ^1.2.5
  device_info_plus: ^10.1.2
  speech_to_text: ^6.6.0
  characters: ^1.4.0
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
